import type {
  Order,
  Carrier,
  Notification,
  StatusHistoryEntry,
  ActivityItem,
} from "./types";

const now = new Date();
function daysAgo(days: number): string {
  const d = new Date(now);
  d.setDate(d.getDate() - days);
  return d.toISOString();
}
function hoursAgo(hours: number): string {
  const d = new Date(now);
  d.setHours(d.getHours() - hours);
  return d.toISOString();
}

export const carriers: Carrier[] = [
  {
    id: "car_01",
    name: "Swift Auto Carriers",
    mc_number: "MC-784523",
    dot_number: "DOT-3291847",
    contact_name: "Mike Reynolds",
    contact_phone: "(305) 555-0147",
    contact_email: "dispatch@swiftauto.com",
    rating: 4.8,
    total_deliveries: 342,
    on_time_percentage: 96,
    insurance_expiry: "2027-03-15",
    created_at: daysAgo(120),
  },
  {
    id: "car_02",
    name: "Pacific Transport LLC",
    mc_number: "MC-651289",
    dot_number: "DOT-2847561",
    contact_name: "Sarah Chen",
    contact_phone: "(415) 555-0293",
    contact_email: "ops@pacifictransport.com",
    rating: 4.6,
    total_deliveries: 218,
    on_time_percentage: 93,
    insurance_expiry: "2026-11-30",
    created_at: daysAgo(90),
  },
  {
    id: "car_03",
    name: "Heartland Auto Movers",
    mc_number: "MC-892341",
    dot_number: "DOT-4129503",
    contact_name: "Tom Bradley",
    contact_phone: "(312) 555-0184",
    contact_email: "tom@heartlandauto.com",
    rating: 4.9,
    total_deliveries: 567,
    on_time_percentage: 98,
    insurance_expiry: "2027-06-22",
    created_at: daysAgo(200),
  },
  {
    id: "car_04",
    name: "Coastal Vehicle Logistics",
    mc_number: "MC-412876",
    dot_number: "DOT-1983724",
    contact_name: "Jennifer Watts",
    contact_phone: "(904) 555-0331",
    contact_email: "jen@coastalvl.com",
    rating: 4.3,
    total_deliveries: 129,
    on_time_percentage: 89,
    insurance_expiry: "2026-09-10",
    created_at: daysAgo(60),
  },
  {
    id: "car_05",
    name: "Summit Express Transport",
    mc_number: "MC-567432",
    dot_number: "DOT-3847291",
    contact_name: "David Park",
    contact_phone: "(720) 555-0219",
    contact_email: "david@summitexpress.com",
    rating: 4.7,
    total_deliveries: 421,
    on_time_percentage: 95,
    insurance_expiry: "2027-01-18",
    created_at: daysAgo(150),
  },
];

export const orders: Order[] = [
  {
    id: "ord_01",
    order_number: "AT-10234",
    status: "delivered",
    customer_name: "James Morrison",
    customer_email: "james.m@email.com",
    customer_phone: "(212) 555-0891",
    vehicle_year: 2022,
    vehicle_make: "BMW",
    vehicle_model: "X5",
    vehicle_vin: "5UXCR6C05N9K78432",
    vehicle_condition: "running",
    origin_city: "New York",
    origin_state: "NY",
    origin_zip: "10001",
    destination_city: "Miami",
    destination_state: "FL",
    destination_zip: "33101",
    distance_miles: 1280,
    carrier_id: "car_01",
    carrier_name: "Swift Auto Carriers",
    driver_name: "Carlos Mendez",
    driver_phone: "(786) 555-0412",
    price: 1450,
    deposit: 350,
    balance_due: 0,
    is_paid: true,
    stripe_payment_id: "pi_3N9kJ2dS8f7h",
    hubspot_deal_id: "hs_deal_8829",
    central_dispatch_id: "CD-772841",
    pickup_date: daysAgo(7),
    delivery_date: daysAgo(2),
    estimated_delivery: daysAgo(3),
    notes: "Customer requested enclosed transport. Delivered in excellent condition.",
    created_at: daysAgo(10),
    updated_at: daysAgo(2),
  },
  {
    id: "ord_02",
    order_number: "AT-10235",
    status: "in_transit",
    customer_name: "Lisa Chen",
    customer_email: "lisa.chen@email.com",
    customer_phone: "(415) 555-0723",
    vehicle_year: 2023,
    vehicle_make: "Tesla",
    vehicle_model: "Model 3",
    vehicle_vin: "5YJ3E1EA3NF29817",
    vehicle_condition: "running",
    origin_city: "San Francisco",
    origin_state: "CA",
    origin_zip: "94102",
    destination_city: "Seattle",
    destination_state: "WA",
    destination_zip: "98101",
    distance_miles: 808,
    carrier_id: "car_02",
    carrier_name: "Pacific Transport LLC",
    driver_name: "Kevin Park",
    driver_phone: "(503) 555-0187",
    price: 950,
    deposit: 250,
    balance_due: 700,
    is_paid: true,
    stripe_payment_id: "pi_4M8nK3eT9g2i",
    hubspot_deal_id: "hs_deal_8834",
    central_dispatch_id: "CD-773102",
    pickup_date: daysAgo(2),
    delivery_date: null,
    estimated_delivery: new Date(now.getTime() + 86400000 * 2).toISOString(),
    notes: "EV — must remain on upper rack. Customer will be at delivery location.",
    created_at: daysAgo(5),
    updated_at: hoursAgo(6),
  },
  {
    id: "ord_03",
    order_number: "AT-10236",
    status: "picked_up",
    customer_name: "Robert Williams",
    customer_email: "r.williams@email.com",
    customer_phone: "(773) 555-0482",
    vehicle_year: 2021,
    vehicle_make: "Ford",
    vehicle_model: "Mustang GT",
    vehicle_vin: "1FA6P8CF2M5122847",
    vehicle_condition: "running",
    origin_city: "Chicago",
    origin_state: "IL",
    origin_zip: "60601",
    destination_city: "Denver",
    destination_state: "CO",
    destination_zip: "80201",
    distance_miles: 1003,
    carrier_id: "car_03",
    carrier_name: "Heartland Auto Movers",
    driver_name: "Bill Watson",
    driver_phone: "(816) 555-0291",
    price: 1100,
    deposit: 300,
    balance_due: 800,
    is_paid: true,
    stripe_payment_id: "pi_5L7mN4fU0h3j",
    hubspot_deal_id: "hs_deal_8841",
    central_dispatch_id: "CD-773287",
    pickup_date: hoursAgo(8),
    delivery_date: null,
    estimated_delivery: new Date(now.getTime() + 86400000 * 3).toISOString(),
    notes: "Sports car — handle with care. Open transport approved.",
    created_at: daysAgo(4),
    updated_at: hoursAgo(8),
  },
  {
    id: "ord_04",
    order_number: "AT-10237",
    status: "dispatched",
    customer_name: "Amanda Torres",
    customer_email: "amanda.t@email.com",
    customer_phone: "(602) 555-0319",
    vehicle_year: 2020,
    vehicle_make: "Toyota",
    vehicle_model: "Camry",
    vehicle_vin: "4T1BF1FK5LU30892",
    vehicle_condition: "running",
    origin_city: "Phoenix",
    origin_state: "AZ",
    origin_zip: "85001",
    destination_city: "Dallas",
    destination_state: "TX",
    destination_zip: "75201",
    distance_miles: 1065,
    carrier_id: "car_05",
    carrier_name: "Summit Express Transport",
    driver_name: "Marcus Johnson",
    driver_phone: "(505) 555-0443",
    price: 875,
    deposit: 200,
    balance_due: 675,
    is_paid: true,
    stripe_payment_id: "pi_6K9oP5gV1i4k",
    hubspot_deal_id: "hs_deal_8847",
    central_dispatch_id: "CD-773401",
    pickup_date: null,
    delivery_date: null,
    estimated_delivery: new Date(now.getTime() + 86400000 * 5).toISOString(),
    notes: "Standard sedan transport. Pickup scheduled for tomorrow AM.",
    created_at: daysAgo(2),
    updated_at: daysAgo(1),
  },
  {
    id: "ord_05",
    order_number: "AT-10238",
    status: "booked",
    customer_name: "David Kim",
    customer_email: "david.kim@email.com",
    customer_phone: "(310) 555-0567",
    vehicle_year: 2024,
    vehicle_make: "Porsche",
    vehicle_model: "911 Carrera",
    vehicle_vin: "WP0AB2A99RS22718",
    vehicle_condition: "running",
    origin_city: "Los Angeles",
    origin_state: "CA",
    origin_zip: "90001",
    destination_city: "Las Vegas",
    destination_state: "NV",
    destination_zip: "89101",
    distance_miles: 270,
    carrier_id: null,
    carrier_name: null,
    driver_name: null,
    driver_phone: null,
    price: 750,
    deposit: 200,
    balance_due: 550,
    is_paid: true,
    stripe_payment_id: "pi_7J0pQ6hW2j5l",
    hubspot_deal_id: "hs_deal_8852",
    central_dispatch_id: null,
    pickup_date: null,
    delivery_date: null,
    estimated_delivery: new Date(now.getTime() + 86400000 * 7).toISOString(),
    notes: "Enclosed transport ONLY. High-value vehicle. Customer very particular.",
    created_at: daysAgo(1),
    updated_at: daysAgo(1),
  },
  {
    id: "ord_06",
    order_number: "AT-10239",
    status: "booked",
    customer_name: "Sarah Mitchell",
    customer_email: "sarah.m@email.com",
    customer_phone: "(404) 555-0891",
    vehicle_year: 2019,
    vehicle_make: "Honda",
    vehicle_model: "CR-V",
    vehicle_vin: "2HKRW2H52KH68923",
    vehicle_condition: "running",
    origin_city: "Atlanta",
    origin_state: "GA",
    origin_zip: "30301",
    destination_city: "Nashville",
    destination_state: "TN",
    destination_zip: "37201",
    distance_miles: 248,
    carrier_id: null,
    carrier_name: null,
    driver_name: null,
    driver_phone: null,
    price: 525,
    deposit: 150,
    balance_due: 375,
    is_paid: true,
    stripe_payment_id: "pi_8I1qR7iX3k6m",
    hubspot_deal_id: "hs_deal_8855",
    central_dispatch_id: null,
    pickup_date: null,
    delivery_date: null,
    estimated_delivery: new Date(now.getTime() + 86400000 * 6).toISOString(),
    notes: "Short haul. Customer flexible on dates.",
    created_at: hoursAgo(12),
    updated_at: hoursAgo(12),
  },
  {
    id: "ord_07",
    order_number: "AT-10240",
    status: "delivered",
    customer_name: "Michael Brown",
    customer_email: "m.brown@email.com",
    customer_phone: "(617) 555-0234",
    vehicle_year: 2021,
    vehicle_make: "Chevrolet",
    vehicle_model: "Tahoe",
    vehicle_vin: "1GNSKBKD8MR38291",
    vehicle_condition: "running",
    origin_city: "Boston",
    origin_state: "MA",
    origin_zip: "02101",
    destination_city: "Charlotte",
    destination_state: "NC",
    destination_zip: "28201",
    distance_miles: 840,
    carrier_id: "car_03",
    carrier_name: "Heartland Auto Movers",
    driver_name: "Jake Torres",
    driver_phone: "(704) 555-0182",
    price: 1050,
    deposit: 275,
    balance_due: 0,
    is_paid: true,
    stripe_payment_id: "pi_9H2rS8jY4l7n",
    hubspot_deal_id: "hs_deal_8820",
    central_dispatch_id: "CD-772512",
    pickup_date: daysAgo(12),
    delivery_date: daysAgo(8),
    estimated_delivery: daysAgo(9),
    notes: "Large SUV. Delivered without issues.",
    created_at: daysAgo(15),
    updated_at: daysAgo(8),
  },
  {
    id: "ord_08",
    order_number: "AT-10241",
    status: "in_transit",
    customer_name: "Emily Davis",
    customer_email: "emily.d@email.com",
    customer_phone: "(503) 555-0678",
    vehicle_year: 2023,
    vehicle_make: "Audi",
    vehicle_model: "Q7",
    vehicle_vin: "WA1LAAF72PD09283",
    vehicle_condition: "running",
    origin_city: "Portland",
    origin_state: "OR",
    origin_zip: "97201",
    destination_city: "Salt Lake City",
    destination_state: "UT",
    destination_zip: "84101",
    distance_miles: 768,
    carrier_id: "car_05",
    carrier_name: "Summit Express Transport",
    driver_name: "Ryan Cole",
    driver_phone: "(208) 555-0391",
    price: 925,
    deposit: 225,
    balance_due: 700,
    is_paid: true,
    stripe_payment_id: "pi_0G3sT9kZ5m8o",
    hubspot_deal_id: "hs_deal_8838",
    central_dispatch_id: "CD-773198",
    pickup_date: daysAgo(1),
    delivery_date: null,
    estimated_delivery: new Date(now.getTime() + 86400000 * 1).toISOString(),
    notes: "Premium SUV. Enclosed transport requested.",
    created_at: daysAgo(3),
    updated_at: hoursAgo(14),
  },
];

export const notifications: Notification[] = [
  {
    id: "notif_01",
    order_id: "ord_01",
    order_number: "AT-10234",
    type: "sms",
    recipient: "(212) 555-0891",
    subject: "Vehicle Delivered",
    message:
      "Hi James, your 2022 BMW X5 has been delivered to Miami, FL. Thank you for choosing our service!",
    status: "sent",
    provider: "twilio",
    created_at: daysAgo(2),
  },
  {
    id: "notif_02",
    order_id: "ord_01",
    order_number: "AT-10234",
    type: "email",
    recipient: "james.m@email.com",
    subject: "Your Vehicle Has Been Delivered — AT-10234",
    message:
      "Dear James, we're pleased to confirm your 2022 BMW X5 has been successfully delivered to Miami, FL.",
    status: "sent",
    provider: "sendgrid",
    created_at: daysAgo(2),
  },
  {
    id: "notif_03",
    order_id: "ord_03",
    order_number: "AT-10236",
    type: "sms",
    recipient: "(773) 555-0482",
    subject: "Vehicle Picked Up",
    message:
      "Hi Robert, your 2021 Ford Mustang GT has been picked up and is now in transit to Denver, CO. Est. delivery: 3 days.",
    status: "sent",
    provider: "twilio",
    created_at: hoursAgo(8),
  },
  {
    id: "notif_04",
    order_id: "ord_03",
    order_number: "AT-10236",
    type: "email",
    recipient: "r.williams@email.com",
    subject: "Your Vehicle Has Been Picked Up — AT-10236",
    message:
      "Dear Robert, your 2021 Ford Mustang GT has been picked up from Chicago, IL and is now in transit.",
    status: "sent",
    provider: "sendgrid",
    created_at: hoursAgo(8),
  },
  {
    id: "notif_05",
    order_id: "ord_02",
    order_number: "AT-10235",
    type: "sms",
    recipient: "(415) 555-0723",
    subject: "Vehicle In Transit",
    message:
      "Hi Lisa, your 2023 Tesla Model 3 is in transit to Seattle, WA. Estimated arrival in 2 days.",
    status: "sent",
    provider: "twilio",
    created_at: hoursAgo(6),
  },
  {
    id: "notif_06",
    order_id: "ord_05",
    order_number: "AT-10238",
    type: "email",
    recipient: "david.kim@email.com",
    subject: "Booking Confirmed — AT-10238",
    message:
      "Dear David, your transport order for 2024 Porsche 911 Carrera from Los Angeles, CA to Las Vegas, NV has been confirmed.",
    status: "sent",
    provider: "sendgrid",
    created_at: daysAgo(1),
  },
  {
    id: "notif_07",
    order_id: "ord_04",
    order_number: "AT-10237",
    type: "sms",
    recipient: "(602) 555-0319",
    subject: "Carrier Dispatched",
    message:
      "Hi Amanda, a carrier has been assigned to your order. Summit Express Transport will pick up your vehicle soon.",
    status: "sent",
    provider: "twilio",
    created_at: daysAgo(1),
  },
];

export const statusHistory: StatusHistoryEntry[] = [
  {
    id: "sh_01",
    order_id: "ord_01",
    order_number: "AT-10234",
    from_status: null,
    to_status: "booked",
    changed_by: "HubSpot Webhook",
    notes: "Order created from HubSpot deal hs_deal_8829",
    created_at: daysAgo(10),
  },
  {
    id: "sh_02",
    order_id: "ord_01",
    order_number: "AT-10234",
    from_status: "booked",
    to_status: "dispatched",
    changed_by: "System",
    notes: "Carrier assigned: Swift Auto Carriers",
    created_at: daysAgo(8),
  },
  {
    id: "sh_03",
    order_id: "ord_01",
    order_number: "AT-10234",
    from_status: "dispatched",
    to_status: "picked_up",
    changed_by: "Central Dispatch Polling",
    notes: "Vehicle picked up — detected via Central Dispatch",
    created_at: daysAgo(7),
  },
  {
    id: "sh_04",
    order_id: "ord_01",
    order_number: "AT-10234",
    from_status: "picked_up",
    to_status: "in_transit",
    changed_by: "System",
    notes: "Auto-transitioned after pickup confirmation",
    created_at: daysAgo(7),
  },
  {
    id: "sh_05",
    order_id: "ord_01",
    order_number: "AT-10234",
    from_status: "in_transit",
    to_status: "delivered",
    changed_by: "Central Dispatch Polling",
    notes: "Delivery confirmed via Central Dispatch",
    created_at: daysAgo(2),
  },
  {
    id: "sh_06",
    order_id: "ord_03",
    order_number: "AT-10236",
    from_status: null,
    to_status: "booked",
    changed_by: "HubSpot Webhook",
    notes: "Order created from HubSpot deal hs_deal_8841",
    created_at: daysAgo(4),
  },
  {
    id: "sh_07",
    order_id: "ord_03",
    order_number: "AT-10236",
    from_status: "booked",
    to_status: "dispatched",
    changed_by: "System",
    notes: "Carrier assigned: Heartland Auto Movers",
    created_at: daysAgo(3),
  },
  {
    id: "sh_08",
    order_id: "ord_03",
    order_number: "AT-10236",
    from_status: "dispatched",
    to_status: "picked_up",
    changed_by: "Central Dispatch Polling",
    notes: "Vehicle picked up — detected via Central Dispatch",
    created_at: hoursAgo(8),
  },
  {
    id: "sh_09",
    order_id: "ord_05",
    order_number: "AT-10238",
    from_status: null,
    to_status: "booked",
    changed_by: "HubSpot Webhook",
    notes: "Order created from HubSpot deal hs_deal_8852",
    created_at: daysAgo(1),
  },
];

export const activities: ActivityItem[] = [
  {
    id: "act_01",
    type: "status_change",
    title: "Vehicle Picked Up",
    description:
      "2021 Ford Mustang GT picked up in Chicago, IL — Heartland Auto Movers",
    order_id: "ord_03",
    order_number: "AT-10236",
    created_at: hoursAgo(8),
  },
  {
    id: "act_02",
    type: "notification",
    title: "SMS Sent",
    description: "Pickup notification sent to Robert Williams",
    order_id: "ord_03",
    order_number: "AT-10236",
    created_at: hoursAgo(8),
  },
  {
    id: "act_03",
    type: "status_change",
    title: "In Transit Update",
    description: "2023 Tesla Model 3 — currently in transit to Seattle, WA",
    order_id: "ord_02",
    order_number: "AT-10235",
    created_at: hoursAgo(6),
  },
  {
    id: "act_04",
    type: "new_order",
    title: "New Order Created",
    description:
      "2024 Porsche 911 Carrera — Los Angeles, CA → Las Vegas, NV",
    order_id: "ord_05",
    order_number: "AT-10238",
    created_at: daysAgo(1),
  },
  {
    id: "act_05",
    type: "payment",
    title: "Deposit Received",
    description: "$200 deposit received via Stripe for order AT-10238",
    order_id: "ord_05",
    order_number: "AT-10238",
    created_at: daysAgo(1),
  },
  {
    id: "act_06",
    type: "status_change",
    title: "Carrier Dispatched",
    description:
      "Summit Express Transport assigned to AT-10237 — Phoenix, AZ → Dallas, TX",
    order_id: "ord_04",
    order_number: "AT-10237",
    created_at: daysAgo(1),
  },
  {
    id: "act_07",
    type: "new_order",
    title: "New Order Created",
    description: "2019 Honda CR-V — Atlanta, GA → Nashville, TN",
    order_id: "ord_06",
    order_number: "AT-10239",
    created_at: hoursAgo(12),
  },
  {
    id: "act_08",
    type: "status_change",
    title: "Vehicle Delivered",
    description:
      "2022 BMW X5 delivered to Miami, FL — Swift Auto Carriers",
    order_id: "ord_01",
    order_number: "AT-10234",
    created_at: daysAgo(2),
  },
];
